import AppKit
import Combine
import ImageIO

/// Watches the system pasteboard and keeps a searchable, pinnable history. Both
/// text and image entries persist across launches — text in the defaults blob,
/// image bytes in `ClipboardImageStore`.
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private weak var settings: SettingsStore?
    private var maxUnpinned: Int { settings?.clipboardMaxItems ?? 100 }
    private let persistKey = "SnapDesk.clipboard.text"
    /// Image METADATA only (id, date, pinned). The bytes are files, under their own
    /// 0700 directory — a base64 image in the defaults plist would be neither
    /// bounded nor 0600.
    private let imagePersistKey = "SnapDesk.clipboard.images"
    private let imageStore = ClipboardImageStore()

    /// Inject settings (max items, enable, store-images).
    func attach(settings: SettingsStore) {
        self.settings = settings
        // Nothing observed "clear history when SnapDesk quits", so switching it ON
        // changed only what the NEXT write would do: the unpinned `.jpg` files and
        // the unpinned plaintext already on disk survived until some incidental
        // persist happened to run — a copy, a star, a delete, or a clean quit. Anyone
        // who turned the switch on because of what was in their history and then
        // force-quit (or crashed, where the quit path never runs) still had all of it
        // on disk, and it came back on the next launch. Rewrite the disk on the
        // transition itself, in both directions, so what is stored always matches
        // what the switch says.
        settings.onClearOnQuitChanged = { [weak self] _ in self?.persistNow() }
    }

    /// Privacy: never capture items that apps explicitly mark as secret or
    /// throwaway. Password managers and the system Keychain set
    /// `org.nspasteboard.ConcealedType`; "transient"/"auto-generated" mark data
    /// that should not be stored in history. Honoring these is the standard
    /// contract every responsible clipboard manager follows.
    private static let sensitivePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
    ]

    /// Best-effort markers for Universal Clipboard / Handoff items.
    private static let universalClipboardTypes: Set<String> = [
        "com.apple.is-remote-clipboard",
        "com.apple.notes.sharedTextEncoded",
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
        loadPersisted()
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
        t.tolerance = 0.2
        // .common: keep polling while a menu or modal is open — the default
        // mode stalls there and copies made meanwhile get lost.
        RunLoop.main.add(t, forMode: .common)
        timer = t
        poll()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        // Optionally wipe unpinned history when the app quits.
        if settings?.clearOnQuit == true {
            items = Self.retainedOnQuit(items)
        }
        flushPersist()   // write any pending (debounced) changes before quit
    }

    // MARK: - Polling

    private func poll() {
        // Time-based auto-delete runs every tick (cheap), even with no new copy.
        purgeExpired()

        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Respect master on/off switch.
        if settings?.clipboardEnabled == false { return }

        let presentTypes = Set((pasteboard.types ?? []).map(\.rawValue))

        // Skip anything flagged secret/transient (passwords, OTPs, etc.) unless
        // the user has explicitly turned that protection off.
        if settings?.ignoreSecrets != false,
           !presentTypes.isDisjoint(with: Self.sensitivePasteboardTypes) { return }

        // Skip Universal Clipboard (Handoff) items, best-effort.
        if settings?.ignoreUniversalClipboard == true,
           !presentTypes.isDisjoint(with: Self.universalClipboardTypes) { return }

        // Skip copies coming from a user-ignored frontmost app.
        if let ignore = settings?.ignoreApps, !ignore.isEmpty,
           let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ignore.contains(front) { return }

        if let string = pasteboard.string(forType: .string),
           !string.isEmpty {
            // Cap in-memory text (~1 MB) — a select-all of a huge log would
            // otherwise retain tens of MB per item in a "lightweight" app. Cap by
            // BYTES: `prefix(1_048_576)` counts characters, so multi-byte text
            // (CJK, emoji) could still keep ~4 MB.
            ingest(.text(ClipboardItem.normalizedForStorage(Self.cappedByBytes(string, 1_048_576))))
        } else if settings?.clipboardStoreImages != false,
                  // PNG first: it is the compressed flavour, so a huge canvas
                  // costs megabytes here instead of the hundreds that an
                  // uncompressed TIFF materialises on the main thread — only to
                  // be thrown away by the size guard below.
                  let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            // Same image copied twice in a row → skip the duplicate row. Hash
            // the WHOLE buffer: two different screenshots of the same window are
            // the same byte length and share a header + first pixel row, so a
            // count-plus-4KB hash collided and silently dropped the second.
            var hasher = Hasher(); hasher.combine(data)
            let hash = hasher.finalize()
            if hash == lastImageHash, case .image = items.first?.kind { return }
            lastImageHash = hash
            // Decompression-bomb guard: read the DECLARED pixel dimensions from
            // the header only (CGImageSource — no decode, no main-thread bitmap
            // materialization) and reject absurd sizes before the off-main decode.
            if let src = CGImageSourceCreateWithData(data as CFData, nil),
               let props = CGImageSourceCopyPropertiesAtIndex(src, 0, nil) as? [CFString: Any] {
                let w = (props[kCGImagePropertyPixelWidth] as? Int) ?? 0
                let h = (props[kCGImagePropertyPixelHeight] as? Int) ?? 0
                if w <= 0 || h <= 0 || w > 30_000 || h > 30_000 || w * h > 60_000_000 { return }
            }
            // Decode + downscale + JPEG-compress OFF the main thread (was a
            // visible hitch on every large image copy), then insert on main. A
            // SERIAL queue, so two images copied in quick succession finish — and
            // therefore insert — in the order they were copied.
            Self.compressQueue.async { [weak self] in
                guard let image = NSImage(data: data),
                      let stored = Self.compressed(image) else { return }
                DispatchQueue.main.async { self?.ingest(stored) }
            }
        }
    }

    /// Draw `img` into a fresh bitmap no larger than `maxPx` on its long edge.
    ///
    /// Sized from the TRUE pixel size, not NSImage.size (which is in POINTS — a 2×
    /// Retina screenshot reports half its pixels there, so scaling off it stored
    /// and pasted the image at half resolution, visibly blurry).
    private static func downscaled(_ img: NSImage, maxPx: CGFloat) -> NSBitmapImageRep? {
        let pxW = CGFloat(img.representations.map(\.pixelsWide).max() ?? Int(img.size.width))
        let pxH = CGFloat(img.representations.map(\.pixelsHigh).max() ?? Int(img.size.height))
        guard pxW > 0, pxH > 0 else { return nil }
        let f = min(1, maxPx / max(pxW, pxH))
        let w = Int(pxW * f), h = Int(pxH * f)
        guard w > 0, h > 0,
              let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: w, pixelsHigh: h,
                                         bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                         isPlanar: false, colorSpaceName: .deviceRGB,
                                         bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        img.draw(in: NSRect(x: 0, y: 0, width: w, height: h),
                 from: .zero, operation: .copy, fraction: 1)
        NSGraphicsContext.restoreGraphicsState()
        return rep
    }

    private static func image(from rep: NSBitmapImageRep) -> NSImage {
        let out = NSImage(size: rep.size)
        out.addRepresentation(rep)
        return out
    }

    /// Downscale to ≤1600 px, JPEG-compress (quality 0.85) and build a ≤320 px
    /// row thumbnail. ~100-300 KB per item instead of tens of MB.
    private static func compressed(_ image: NSImage) -> ClipboardItem.Kind? {
        guard let full = downscaled(image, maxPx: 1600),
              let thumbRep = downscaled(image, maxPx: 320) else { return nil }
        // JPEG has no alpha channel, so a transparent logo came back with every
        // transparent pixel solid BLACK — while the row's thumbnail, built from
        // the un-encoded bitmap, still looked right. PNG for anything carrying
        // transparency; JPEG stays the default because most copies are photos
        // and screenshots, where it is a fraction of the size.
        guard let data = full.hasAlpha
                ? full.representation(using: .png, properties: [:])
                : full.representation(using: .jpeg, properties: [.compressionFactor: 0.85])
        else { return nil }
        return .image(data: data, thumb: Self.image(from: thumbRep))
    }

    /// Rebuild a row from bytes already on disk: the JPEG is kept as-is (it was
    /// compressed once, at copy time — re-encoding it would only lose quality) and
    /// only the row thumbnail is regenerated.
    private static func restoredKind(from data: Data) -> ClipboardItem.Kind? {
        guard let image = NSImage(data: data),
              let rep = downscaled(image, maxPx: 320) else { return nil }
        return .image(data: data, thumb: Self.image(from: rep))
    }

    private func ingest(_ kind: ClipboardItem.Kind) {
        if case .text(let new) = kind {
            if settings?.rejectDuplicates != false {
                // Any existing identical text → move it to the top (refresh time)
                // instead of storing a duplicate.
                if let idx = items.firstIndex(where: {
                    if case .text(let s) = $0.kind { return s == new }; return false
                }) {
                    let old = items.remove(at: idx)
                    items.insert(ClipboardItem(id: old.id, kind: old.kind, date: Date(), pinned: old.pinned), at: 0)
                    trim()
                    persist()
                    return
                }
            } else if case .text(let existing)? = items.first?.kind, existing == new {
                return   // de-dupe consecutive identical only
            }
        }
        items.insert(ClipboardItem(kind: kind), at: 0)
        trim()
        persist()
    }

    private var lastImageHash: Int?
    private var purgeTick = 0
    /// Serial so image compressions insert in copy order.
    private static let compressQueue = DispatchQueue(label: "com.snapdesk.clipboard.compress", qos: .utility)

    /// Auto-delete unpinned items older than the configured window. Throttled to
    /// ~every 10s (not every 0.5s poll) since the cutoff is hour-granular.
    private func purgeExpired() {
        guard let hrs = settings?.autoDeleteHours, hrs > 0 else { return }
        purgeTick += 1
        guard purgeTick % 20 == 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(hrs) * 3600)
        let before = items.count
        items.removeAll { !$0.pinned && $0.date < cutoff }
        if items.count != before { persist() }
    }

    private func trim() { items = Self.trimmed(items, cap: maxUnpinned) }

    /// The cap counts CAPTURED, unstarred rows only.
    ///
    /// Starred items are exempt (that is what starring means), and so is anything
    /// the person authored: a snippet is not a trace of copying and evicting one
    /// would silently destroy something they typed. Internal for tests.
    static func trimmed(_ items: [ClipboardItem], cap: Int) -> [ClipboardItem] {
        var unpinnedCount = 0
        return items.filter { item in
            if item.pinned || item.isSnippet { return true }
            unpinnedCount += 1
            return unpinnedCount <= cap
        }
    }

    /// What survives "clear history when SnapDesk quits": starred rows, plus
    /// anything authored. The setting is about traces of copying, not about
    /// content the person wrote themselves. Internal for tests.
    static func retainedOnQuit(_ items: [ClipboardItem]) -> [ClipboardItem] {
        items.filter { $0.pinned || $0.isSnippet }
    }

    // MARK: - Actions

    /// What a paste should actually emit.
    ///
    /// Copied text routinely arrives with a trailing newline — selecting a whole
    /// line in a terminal or an editor, a table cell, a chat message. Pasting it
    /// verbatim re-emits that newline: the caret drops to the START OF THE NEXT
    /// LINE instead of staying where the text landed, and in a message field it
    /// sends. History keeps the original bytes; only what goes on the pasteboard
    /// is trimmed, and only at the very END, so a code block's indentation and
    /// its internal line breaks survive untouched.
    ///
    /// `Character.isNewline` covers "\n", "\r", "\r\n" (one grapheme) and the
    /// Unicode line/paragraph separators.
    /// Internal for tests — see PasteboardTextTests.
    static func pasteboardText(_ s: String) -> String {
        var t = s
        while let last = t.last, last.isNewline { t.removeLast() }
        // An item that is nothing but newlines would paste nothing at all.
        return t.isEmpty ? s : t
    }

    /// Truncate to at most `maxBytes` of UTF-8, on a character boundary (never
    /// splits a multi-byte scalar). Returns the string unchanged when it fits.
    /// Internal for tests.
    static func cappedByBytes(_ s: String, _ maxBytes: Int) -> String {
        guard s.utf8.count > maxBytes else { return s }
        var end = s.startIndex, bytes = 0
        for i in s.indices {
            let n = String(s[i]).utf8.count
            if bytes + n > maxBytes { break }
            bytes += n; end = s.index(after: i)
        }
        return String(s[s.startIndex..<end])
    }

    /// Copies an item back to the pasteboard (without re-adding it to history).
    ///
    /// - Parameter movingToTop: whether this counts as a fresh copy and should
    ///   promote the item to the top of the history. True for an explicit
    ///   re-copy (double-click); false when the item is only being routed
    ///   through the pasteboard on its way to a paste, because renumbering the
    ///   list under the user's cursor there makes every following row move.
    func copyToPasteboard(_ item: ClipboardItem, movingToTop: Bool = false) {
        pasteboard.clearContents()
        switch item.kind {
        case .text(let s):
            let out = Self.pasteboardText(s)
            pasteboard.setString(out, forType: .string)
            // Links also get the URL flavor — apps that read `public.url`
            // (browsers, Finder's Go-to, link fields) then paste it natively
            // instead of falling back to plain text. Only when it's a real
            // absolute URL: a scheme-less "www.…" written to public.url is
            // invalid and some apps then paste nothing at all.
            if item.contentType == .link, let url = URL(string: out), url.scheme != nil {
                pasteboard.setString(out, forType: .URL)
            }
        case .image(let data, _):
            // `clearContents()` has already run, so a write that fails leaves
            // the pasteboard EMPTY — whatever the person had is gone and the
            // next ⌘V pastes nothing. Say so rather than wiping in silence.
            guard let img = NSImage(data: data), pasteboard.writeObjects([img]) else {
                Notifier.error("Copy failed", "That image couldn't be read.")
                lastChangeCount = pasteboard.changeCount
                return
            }
        }
        // Claim the change so the monitor doesn't read our own write back and
        // file it as a fresh copy.
        lastChangeCount = pasteboard.changeCount
        guard movingToTop, let idx = items.firstIndex(of: item), idx != 0 else { return }
        let moved = items.remove(at: idx)
        items.insert(moved, at: 0)
        persist()
    }

    /// Adds text composed inside SnapDesk — today, the merge of several rows.
    ///
    /// Goes through `ingest` so it obeys the same duplicate rule, byte cap and trim
    /// as a real copy. Deliberately does NOT touch the pasteboard: merging is
    /// collecting, and silently replacing what the person has copied would be a
    /// surprise from a button that says "Merge".
    func add(text: String) {
        guard text.isEmpty == false else { return }
        ingest(.text(Self.cappedByBytes(text, 1_048_576)))
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(of: item) else { return }
        items[idx].pinned.toggle()
        persist()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0 == item }
        persist()
    }

    func clearUnpinned() {
        items.removeAll { !$0.pinned }
        persist()
    }

    func clearAll() {
        // "Lock Starred Items": pinned items survive even a full clear.
        if settings?.lockPinned != false {
            items.removeAll { !$0.pinned }
        } else {
            items.removeAll()
        }
        persist()
    }

    // MARK: - Persistence

    /// Internal for tests.
    struct Persisted: Codable {
        let id: UUID
        let text: String
        let date: Date
        let pinned: Bool
    }

    /// An image row's metadata. The bytes live in `ClipboardImageStore` under this
    /// same id; this only records that the row existed and how it was filed.
    /// Internal for tests.
    struct PersistedImage: Codable {
        let id: UUID
        let date: Date
        let pinned: Bool
    }

    private var saveWork: DispatchWorkItem?
    /// One serial queue owns every write. A debounced write and the quit-time
    /// flush used to run on different queues, so a late debounced write could
    /// land AFTER the flush and resurrect cleared/deleted history. Serializing
    /// them makes the last-scheduled write the last-executed write.
    private static let persistQueue = DispatchQueue(label: "com.snapdesk.clipboard.persist")
    /// Total on-disk budget for history text (UTF-8 bytes). Bounds both the
    /// plist size and the synchronous decode at launch.
    private static let persistByteBudget = 8_388_608   // 8 MB

    /// Debounced: rapid copies and clicks must never hitch the UI on a write.
    private func persist() {
        let work = persistWork()
        saveWork?.cancel()
        saveWork = work
        Self.persistQueue.asyncAfter(deadline: .now() + 0.8, execute: work)
    }

    /// Write without waiting out the debounce, still off the main thread.
    ///
    /// For changes whose whole point is that they take effect NOW — switching
    /// "clear history when SnapDesk quits" on has to purge what is already on disk.
    /// Cancelling the pending debounced work matters as much as the new write: that
    /// one was snapshotted while the flag was still false and would otherwise land
    /// 0.8 s later and write the unpinned bytes straight back.
    private func persistNow() {
        let work = persistWork()
        saveWork?.cancel()
        saveWork = work
        Self.persistQueue.async(execute: work)
    }

    /// Flush any pending save immediately and synchronously (used on quit).
    private func flushPersist() {
        let work = persistWork()
        saveWork?.cancel()
        Self.persistQueue.sync(execute: work)
    }

    /// Snapshot everything on the main thread (cheap — refs and a plan), then do
    /// the encoding, the plist write, the image writes and the orphan prune on the
    /// persist queue. ONE serial queue owns the plist AND the image directory, so a
    /// debounced write, the quit-time flush and a prune can never interleave.
    private func persistWork() -> DispatchWorkItem {
        let pinnedOnly = pinnedOnlyOnDisk
        let snapshot = Self.persistSnapshot(items, cap: maxUnpinned, pinnedOnly: pinnedOnly)
        // Text is safe to write at any moment. The image half is NOT: while a
        // restore is outstanding `items` has no image rows yet, so a plan built from
        // it is empty — and that emptied the manifest and deleted every stored
        // `.jpg`, on the persist queue, while the restore loop was still reading
        // those very files off `compressQueue`. Whatever it had not reached was gone
        // for good: those bytes had never been in memory. See `imagesRestorePending`.
        let entries = imagesRestorePending
            ? nil
            : ClipboardImageStore.plan(items, pinnedOnly: pinnedOnly)
        // Metadata for exactly what the plan allows on disk, so the manifest and
        // the directory can never disagree: an entry with no file is a row that
        // comes back blank, a file with no entry is an orphan.
        let meta = entries.map { Self.imageSnapshot(items, keeping: Set($0.map(\.id))) }
        let key = persistKey, imageKey = imagePersistKey, store = imageStore
        return DispatchWorkItem {
            Self.write(snapshot, key: key)
            guard let entries, let meta else { return }
            Self.writeImageMeta(meta, key: imageKey)
            store.synchronize(entries, prune: true)
        }
    }

    /// With "Clear history when SnapDesk quits" on, unpinned content must NEVER
    /// reach the disk — neither text nor image bytes — because a crash or
    /// force-quit (where `stop()` never runs) would leave the whole history
    /// behind. So persist pinned only.
    private var pinnedOnlyOnDisk: Bool { settings?.clearOnQuit == true }

    /// Text items only, filtered FIRST (images no longer eat the quota), pinned
    /// items first (kept preferentially), huge strings capped at 512 KB, and a
    /// hard aggregate byte budget so the plist can't grow without bound.
    /// Internal for tests.
    static func persistSnapshot(_ items: [ClipboardItem], cap: Int, pinnedOnly: Bool) -> [Persisted] {
        func persisted(_ item: ClipboardItem) -> Persisted? {
            // A snippet row has its own store and its own blob; writing it here too
            // would resurrect a deleted snippet as a history entry on next launch.
            guard case .text(let raw) = item.kind, item.isSnippet == false else { return nil }
            let text = raw.utf8.count > 524_288 ? cappedByBytes(raw, 524_288) : raw
            return Persisted(id: item.id, text: text, date: item.date, pinned: item.pinned)
        }
        var out: [Persisted] = []
        var bytes = 0
        // Pinned first so the budget never sacrifices a starred item for recents.
        let pinned = items.filter { $0.pinned }
        let unpinned: [ClipboardItem] = pinnedOnly ? [] : Array(items.filter { !$0.pinned }.prefix(max(cap, 200)))
        for item in pinned + unpinned {
            guard let p = persisted(item) else { continue }
            bytes += p.text.utf8.count
            if bytes > persistByteBudget && !p.pinned { continue }
            out.append(p)
        }
        return out
    }

    /// Metadata for exactly the images `ClipboardImageStore.plan` allows on disk.
    /// Internal for tests.
    static func imageSnapshot(_ items: [ClipboardItem], keeping ids: Set<UUID>) -> [PersistedImage] {
        items.compactMap { item in
            guard item.isImage, ids.contains(item.id) else { return nil }
            return PersistedImage(id: item.id, date: item.date, pinned: item.pinned)
        }
    }

    private static func write(_ items: [Persisted], key: String) {
        do {
            let data = try JSONEncoder().encode(items)
            UserDefaults.standard.set(data, forKey: key)
        } catch {
            NSLog("SnapDesk: failed to persist clipboard history: \(error)")
        }
    }

    private static func writeImageMeta(_ items: [PersistedImage], key: String) {
        do {
            let data = try JSONEncoder().encode(items)
            UserDefaults.standard.set(data, forKey: key)
        } catch {
            NSLog("SnapDesk: failed to persist clipboard image index: \(error)")
        }
    }

    private func loadPersisted() {
        defer { loadPersistedImages() }
        guard let data = UserDefaults.standard.data(forKey: persistKey),
              let saved = try? JSONDecoder().decode([Persisted].self, from: data) else { return }
        // Normalize on load too — links saved before trailing-newline trimming
        // existed would otherwise keep their broken paste behavior forever.
        items = saved.map {
            ClipboardItem(id: $0.id, kind: .text(ClipboardItem.normalizedForStorage($0.text)),
                          date: $0.date, pinned: $0.pinned)
        }
    }

    /// Safety ceiling on restore. The real bound is the store's byte budget, which
    /// the manifest already respects; this only stops an old or hand-edited
    /// manifest from turning launch into a thousand JPEG decodes.
    private static let maxRestoredImages = 300

    /// Image rows come back ASYNCHRONOUSLY: decoding a list of screenshots into row
    /// thumbnails is the most expensive thing available at launch, and the history
    /// window is not on screen yet. Same off-main queue the compression path uses.
    private func loadPersistedImages() {
        guard let data = UserDefaults.standard.data(forKey: imagePersistKey),
              let meta = try? JSONDecoder().decode([PersistedImage].self, from: data),
              meta.isEmpty == false else { return }
        let wanted = meta.sorted { $0.date > $1.date }.prefix(Self.maxRestoredImages)
        let store = imageStore
        // Set BEFORE the hop: a copy one millisecond from now must already find the
        // restore outstanding, or its persist prunes the files this loop reads.
        imagesRestorePending = true
        Self.compressQueue.async { [weak self] in
            var restored: [ClipboardItem] = []
            for entry in wanted {
                // A missing file is not an error: the directory may have been
                // pruned, or the person may have cleared it by hand.
                guard let bytes = store.data(for: entry.id),
                      let kind = Self.restoredKind(from: bytes) else { continue }
                restored.append(ClipboardItem(id: entry.id, kind: kind,
                                              date: entry.date, pinned: entry.pinned))
            }
            // Always hops back, even with nothing to merge: the flag has to be
            // cleared or no persist would ever prune the image directory again.
            DispatchQueue.main.async { self?.finishImageRestore(restored) }
        }
    }

    /// True from the moment the image restore is dispatched until its rows are back
    /// in `items`. Main-thread only — see `persistWork()` for what it guards.
    private var imagesRestorePending = false

    private func finishImageRestore(_ restored: [ClipboardItem]) {
        imagesRestorePending = false
        if restored.isEmpty == false { merge(restored: restored) }
        // Any prune that was skipped while the restore was outstanding still owes the
        // person their promise: with clear-on-quit on, unpinned bytes must not be
        // left sitting on disk waiting for the next incidental write.
        if pinnedOnlyOnDisk { persistNow() }
    }

    /// Splice restored image rows into the loaded text history by date, so the list
    /// reads in the order things were actually copied. Anything copied while the
    /// decode was running keeps its place — matching by id, never by position.
    ///
    /// No `persist()` here: nothing about what is on disk changed, and writing from
    /// a load would mean a launch that crashes mid-restore could shorten history.
    private func merge(restored: [ClipboardItem]) {
        let known = Set(items.map(\.id))
        items = (items + restored.filter { known.contains($0.id) == false })
            .sorted { $0.date > $1.date }
        trim()
    }
}
