import AppKit
import Combine

/// Watches the system pasteboard and keeps a searchable, pinnable history.
/// Text entries persist across launches; image entries are session-only.
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private weak var settings: SettingsStore?
    private var maxUnpinned: Int { settings?.clipboardMaxItems ?? 100 }
    private let persistKey = "SnapDesk.clipboard.text"

    /// Inject settings (max items, enable, store-images).
    func attach(settings: SettingsStore) { self.settings = settings }

    /// Privacy: never capture items that apps explicitly mark as secret or
    /// throwaway. Password managers (1Password, Keychain, etc.) set
    /// `org.nspasteboard.ConcealedType`; "transient"/"auto-generated" mark data
    /// that should not be stored in history. Honoring these is the standard
    /// contract every responsible clipboard manager follows.
    private static let sensitivePasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
    ]

    /// Best-effort markers for Universal Clipboard / Handoff items.
    private static let universalClipboardTypes: Set<String> = [
        "com.apple.is-remote-clipboard",
        "com.apple.notes.sharedTextEncoded",
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
        loadPersisted()
    }

    func start() {
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
        t.tolerance = 0.2
        // .common: keep polling while a menu or modal is open — the default
        // mode stalls there and copies made meanwhile get lost.
        RunLoop.main.add(t, forMode: .common)
        timer = t
        poll()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        // Optionally wipe unpinned history when the app quits.
        if settings?.clearOnQuit == true {
            items.removeAll { !$0.pinned }
        }
        flushPersist()   // write any pending (debounced) changes before quit
    }

    // MARK: - Polling

    private func poll() {
        // Time-based auto-delete runs every tick (cheap), even with no new copy.
        purgeExpired()

        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Respect master on/off switch.
        if settings?.clipboardEnabled == false { return }

        let presentTypes = Set((pasteboard.types ?? []).map(\.rawValue))

        // Skip anything flagged secret/transient (passwords, OTPs, etc.) unless
        // the user has explicitly turned that protection off.
        if settings?.ignoreSecrets != false,
           !presentTypes.isDisjoint(with: Self.sensitivePasteboardTypes) { return }

        // Skip Universal Clipboard (Handoff) items, best-effort.
        if settings?.ignoreUniversalClipboard == true,
           !presentTypes.isDisjoint(with: Self.universalClipboardTypes) { return }

        // Skip copies coming from a user-ignored frontmost app.
        if let ignore = settings?.ignoreApps, !ignore.isEmpty,
           let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ignore.contains(front) { return }

        if let string = pasteboard.string(forType: .string),
           !string.isEmpty {
            // Cap in-memory text (~1 MB) — a select-all of a huge log would
            // otherwise retain tens of MB per item in a "lightweight" app.
            let capped = string.utf8.count > 1_048_576 ? String(string.prefix(1_048_576)) : string
            ingest(.text(capped))
        } else if settings?.clipboardStoreImages != false,
                  let data = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
            // Same image copied twice in a row → skip the duplicate row.
            let hash = data.count ^ (data.prefix(4096).hashValue)
            if hash == lastImageHash, case .image = items.first?.kind { return }
            lastImageHash = hash
            // Decompression-bomb guard: reject before decoding if the DECLARED
            // pixel dimensions are absurd (a 20k×20k image would decode to GBs).
            if let rep = NSBitmapImageRep.imageReps(with: data).first {
                let w = rep.pixelsWide, h = rep.pixelsHigh
                if w <= 0 || h <= 0 || w > 30_000 || h > 30_000 || w * h > 60_000_000 { return }
            }
            // Decode + downscale + JPEG-compress OFF the main thread (was a
            // visible hitch on every large image copy), then insert on main.
            DispatchQueue.global(qos: .utility).async { [weak self] in
                guard let image = NSImage(data: data),
                      let stored = Self.compressed(image) else { return }
                DispatchQueue.main.async { self?.ingest(stored) }
            }
        }
    }

    /// Downscale to ≤1600 px, JPEG-compress (quality 0.85) and build a ≤320 px
    /// row thumbnail. ~100-300 KB per item instead of tens of MB.
    private static func compressed(_ image: NSImage) -> ClipboardItem.Kind? {
        func bitmap(_ img: NSImage, maxPx: CGFloat) -> NSBitmapImageRep? {
            let s = img.size
            guard s.width > 0, s.height > 0 else { return nil }
            let f = min(1, maxPx / max(s.width, s.height))
            let w = Int(s.width * f), h = Int(s.height * f)
            guard let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: w, pixelsHigh: h,
                                             bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                             isPlanar: false, colorSpaceName: .deviceRGB,
                                             bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
            NSGraphicsContext.saveGraphicsState()
            NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
            img.draw(in: NSRect(x: 0, y: 0, width: w, height: h),
                     from: .zero, operation: .copy, fraction: 1)
            NSGraphicsContext.restoreGraphicsState()
            return rep
        }
        guard let full = bitmap(image, maxPx: 1600),
              let data = full.representation(using: .jpeg, properties: [.compressionFactor: 0.85]),
              let thumbRep = bitmap(image, maxPx: 320) else { return nil }
        let thumb = NSImage(size: thumbRep.size)
        thumb.addRepresentation(thumbRep)
        return .image(data: data, thumb: thumb)
    }

    private func ingest(_ kind: ClipboardItem.Kind) {
        if case .text(let new) = kind {
            if settings?.rejectDuplicates != false {
                // Any existing identical text → move it to the top (refresh time)
                // instead of storing a duplicate.
                if let idx = items.firstIndex(where: {
                    if case .text(let s) = $0.kind { return s == new }; return false
                }) {
                    let old = items.remove(at: idx)
                    items.insert(ClipboardItem(id: old.id, kind: old.kind, date: Date(), pinned: old.pinned), at: 0)
                    trim()
                    persist()
                    return
                }
            } else if case .text(let existing)? = items.first?.kind, existing == new {
                return   // de-dupe consecutive identical only
            }
        }
        items.insert(ClipboardItem(kind: kind), at: 0)
        trim()
        persist()
    }

    private var lastImageHash: Int?
    private var purgeTick = 0

    /// Auto-delete unpinned items older than the configured window. Throttled to
    /// ~every 10s (not every 0.5s poll) since the cutoff is hour-granular.
    private func purgeExpired() {
        guard let hrs = settings?.autoDeleteHours, hrs > 0 else { return }
        purgeTick += 1
        guard purgeTick % 20 == 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(hrs) * 3600)
        let before = items.count
        items.removeAll { !$0.pinned && $0.date < cutoff }
        if items.count != before { persist() }
    }

    private func trim() {
        var unpinnedCount = 0
        items = items.filter { item in
            if item.pinned { return true }
            unpinnedCount += 1
            return unpinnedCount <= maxUnpinned
        }
    }

    // MARK: - Actions

    /// Copies an item back to the pasteboard (without re-adding it to history).
    func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text(let s): pasteboard.setString(s, forType: .string)
        case .image(let data, _):
            if let img = NSImage(data: data) { pasteboard.writeObjects([img]) }
        }
        lastChangeCount = pasteboard.changeCount
        // Move it to the top.
        if let idx = items.firstIndex(of: item) {
            let moved = items.remove(at: idx)
            items.insert(moved, at: 0)
            persist()
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(of: item) else { return }
        items[idx].pinned.toggle()
        persist()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0 == item }
        persist()
    }

    func clearUnpinned() {
        items.removeAll { !$0.pinned }
        persist()
    }

    func clearAll() {
        // "Lock Starred Items": pinned items survive even a full clear.
        if settings?.lockPinned != false {
            items.removeAll { !$0.pinned }
        } else {
            items.removeAll()
        }
        persist()
    }

    // MARK: - Persistence (text only)

    private struct Persisted: Codable {
        let id: UUID
        let text: String
        let date: Date
        let pinned: Bool
    }

    private var saveWork: DispatchWorkItem?

    /// Snapshot the text items on the main thread (cheap — just refs), then
    /// debounce + JSON-encode + write OFF the main thread so rapid copies/clicks
    /// never hitch the UI.
    private func persist() {
        let snapshot = Self.persistSnapshot(items, cap: maxUnpinned)
        saveWork?.cancel()
        let key = persistKey
        let work = DispatchWorkItem { Self.write(snapshot, key: key) }
        saveWork = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.8, execute: work)
    }

    /// Flush any pending save immediately and synchronously (used on quit).
    private func flushPersist() {
        saveWork?.cancel()
        let snapshot = Self.persistSnapshot(items, cap: maxUnpinned)
        Self.write(snapshot, key: persistKey)
    }

    /// Text items only, filtered FIRST (images no longer eat the quota), every
    /// pinned item always included, huge strings capped at 512 KB so the
    /// UserDefaults plist stays sane.
    private static func persistSnapshot(_ items: [ClipboardItem], cap: Int) -> [Persisted] {
        var out: [Persisted] = []
        var unpinned = 0
        for item in items {
            guard case .text(let raw) = item.kind else { continue }
            if !item.pinned {
                unpinned += 1
                if unpinned > max(cap, 200) { continue }
            }
            let text = raw.count > 524_288 ? String(raw.prefix(524_288)) : raw
            out.append(Persisted(id: item.id, text: text, date: item.date, pinned: item.pinned))
        }
        return out
    }

    private static func write(_ items: [Persisted], key: String) {
        do {
            let data = try JSONEncoder().encode(items)
            UserDefaults.standard.set(data, forKey: key)
        } catch {
            NSLog("SnapDesk: failed to persist clipboard history: \(error)")
        }
    }

    private func loadPersisted() {
        guard let data = UserDefaults.standard.data(forKey: persistKey),
              let saved = try? JSONDecoder().decode([Persisted].self, from: data) else { return }
        items = saved.map {
            ClipboardItem(id: $0.id, kind: .text($0.text), date: $0.date, pinned: $0.pinned)
        }
    }
}
